"""jobsda delete qilish jooy;ar i o'zgartirildi 

Revision ID: 1ffb69b58208
Revises: 0819a52ddf6d
Create Date: 2026-07-06 13:00:54.940540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ffb69b58208'
down_revision: Union[str, Sequence[str], None] = '0819a52ddf6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('OPEN', 'CLOSED', 'DRAFT', name='jobstatus').create(op.get_bind())
    op.add_column('jobs', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('OPEN', 'CLOSED', 'DRAFT', name='jobstatus'),
               existing_nullable=False,
               postgresql_using='status::jobstatus')
    op.alter_column('jobs', 'posted_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('jobs_posted_by_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'users', ['posted_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_posted_by_id_fkey'), 'jobs', 'users', ['posted_by_id'], ['id'], ondelete='CASCADE')
    op.alter_column('jobs', 'posted_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'status',
               existing_type=sa.Enum('OPEN', 'CLOSED', 'DRAFT', name='jobstatus'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.drop_column('jobs', 'is_deleted')
    sa.Enum('OPEN', 'CLOSED', 'DRAFT', name='jobstatus').drop(op.get_bind())
    # ### end Alembic commands ###
