"""initial commit

Revision ID: 2d43fcf0b0f1
Revises: c74407c61540
Create Date: 2026-06-22 19:16:01.934883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d43fcf0b0f1'
down_revision: Union[str, Sequence[str], None] = 'c74407c61540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ali', sa.String(length=1100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'ali')
    # ### end Alembic commands ###
