"""empty message

Revision ID: cc85ca79d79e
Revises: 25a35b540aff
Create Date: 2026-06-23 18:10:12.727642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc85ca79d79e'
down_revision: Union[str, Sequence[str], None] = '25a35b540aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'ali')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ali', sa.VARCHAR(length=1100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
